# Generated by Django 2.2.7 on 2019-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191107_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_number_completed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
