# Generated by Django 2.2.7 on 2019-11-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191107_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='number_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=9),
            preserve_default=False,
        ),
    ]
