# Generated by Django 2.2.7 on 2019-11-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_habit_number_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='total_success_number',
            new_name='total_number',
        ),
    ]
