# Generated by Django 2.2.7 on 2019-11-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20191109_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_number_completed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
