# Generated by Django 2.2.7 on 2019-11-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20191109_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_log', to='tracker.Habit'),
        ),
    ]
