# Generated by Django 2.2.7 on 2019-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20191109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='total_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
