# Generated by Django 2.2.7 on 2019-11-11 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20191110_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['log_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_comments', to='tracker.Log'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_supporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
